### ISSUE TITLE
Frontend Validation in ABDM Id creation form is unintentionally triggered

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_abdm_fe#1]
![Image](https://github.com/user-attachments/assets/7618a813-e149-4c72-88b9-f9c417743204)

- [ ] when we are trying to create a new ABDM id, and post submission of the ID number, the frontend is throw "value cannot be greater than 16" error in the frontend

**Comment by JavidSumra** [comment]
Hey @nihal467 can you please assign it to me?
cc @khavinshankar
